import NavBar from '../components/layout/navbar'
import Footer from '@/components/layout/footer';
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { ReactNode, Suspense } from 'react';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <NavBar />
        <Suspense>
          <main>{children}</main>
        </Suspense>
        <Footer />
      </body>
    </html>
  )
}
